import { createRenaultR35Mesh as createRenaultR35Base } from './RenaultR35.js';
import { createRenaultD2Mesh as createRenaultD2Base } from './RenaultD2.js';
import { createSomuaS35Mesh as createSomuaS35Base } from './SomuaS35.js';
import { createHotchkissH39Mesh as createHotchkissH39Base } from './HotchkissH39.js';
import { createAMC35Mesh as createAMC35Base } from './AMC35.js';
import { createPanhard178Mesh as createPanhard178Base } from './Panhard178.js';
import { createLafflyS20TLMesh as createLafflyS20TLBase } from './LafflyS20TL.js';
import { createCharB1BisMesh as createCharB1BisBase } from './CharB1Bis.js';
import { createPanzerIIMesh as createPanzerIIBase } from './PanzerII.js';
import { createPanzerIIIMesh as createPanzerIIIBase } from './PanzerIII.js';
import { createPanzer35tMesh as createPanzer35tBase } from './Panzer35t.js';
import { createPanzer38tMesh as createPanzer38tBase } from './Panzer38t.js';
import { createSdKfz231Mesh as createSdKfz231Base } from './SdKfz231.js';
import { createOpelBlitzMesh as createOpelBlitzBase } from './OpelBlitz.js';
import { createPanzerIVMesh as createPanzerIVBase } from './PanzerIV.js';
import { enhanceVehicleModel } from './VehicleModelEnhancer.js';

export const createRenaultR35Mesh = options => enhanceVehicleModel(createRenaultR35Base(), options);
export const createRenaultD2Mesh = options => createRenaultD2Base(options);
export const createSomuaS35Mesh = options => enhanceVehicleModel(createSomuaS35Base(), options);
export const createHotchkissH39Mesh = options => enhanceVehicleModel(createHotchkissH39Base(), options);
export const createAMC35Mesh = options => enhanceVehicleModel(createAMC35Base(), options);
export const createPanhard178Mesh = options => enhanceVehicleModel(createPanhard178Base(), options);
export const createLafflyS20TLMesh = options => enhanceVehicleModel(createLafflyS20TLBase(), options);
export const createCharB1BisMesh = options => enhanceVehicleModel(createCharB1BisBase(), options);
export const createPanzerIIMesh = options => enhanceVehicleModel(createPanzerIIBase(), options);
export const createPanzerIIIMesh = options => enhanceVehicleModel(createPanzerIIIBase(), options);
export const createPanzer35tMesh = options => enhanceVehicleModel(createPanzer35tBase(), options);
export const createPanzer38tMesh = options => enhanceVehicleModel(createPanzer38tBase(), options);
export const createSdKfz231Mesh = options => enhanceVehicleModel(createSdKfz231Base(), options);
export const createOpelBlitzMesh = options => enhanceVehicleModel(createOpelBlitzBase(), options);
export const createPanzerIVMesh = options => enhanceVehicleModel(createPanzerIVBase(), options);
