const freezeWeapon = (weapon) => Object.freeze({
  burstSize: 1,
  cyclicRPM: weapon.practicalRPM,
  dragPerSecond: 0.08,
  dispersionMOA: 3,
  maxRange: 500,
  tracerEvery: 4,
  explosiveRadius: 0,
  penetrationMmAt100m: 0,
  penetrationVelocityExponent: 1.35,
  ...weapon
});

const FRENCH_8MM_RIFLE_GAMEPLAY_APPROXIMATION = Object.freeze({
  muzzleVelocity: 823,
  projectileMassKg: 0.009,
  practicalRPM: 15,
  reloadSeconds: 3.8,
  dispersionMOA: 2.8,
  maxRange: 500,
  woundDamage: 112
});

const FRENCH_8MM_RIFLE_BALLISTICS_QUALITY =
  'gameplay approximation reusing the current MAS-36 family ballistic and cadence baseline; not historical 8 mm firing data';
const LEBEL_MUSEUM_REFERENCE =
  'https://www.musee-armee.fr/fileadmin/user_upload/Documents/Support-Visite-Fiches-Objets/Fiches-1914-1918/MA_fiche-objet-Lebel.pdf';
const BERTHIER_MUSEUM_REFERENCE =
  'https://www.musee-armee.fr/magazine/systeme-berthier-armes-iconiques-de-larmee-francaise-1.html';
const BERTHIER_1940_MUSEUM_REFERENCE =
  'https://www.musee-armee.fr/fileadmin/user_upload/Documents/Rapports-Activites/MA_Rapport-Activite-2010.pdf#page=49';
const APX_1916_MUSEUM_REFERENCE =
  'https://collections.musee-armee.fr/harceler-lennemi-pendant-la-premiere-guerre-mondiale/';
const BRANDT_MLE1935_MANUAL_REFERENCE =
  'https://bibliotheques-numeriques.defense.gouv.fr/mediatheque-en/docu'
  + 'ment/f917220f-7588-4e68-ab19-491e4dd36839?cote=Doc.+Regl.+342&portal=365729';

export const FRANCE_1940_WEAPONS = Object.freeze({
  MAS36: freezeWeapon({
    id: 'MAS36',
    name: 'MAS-36 Rifle',
    kind: 'rifle',
    cartridge: '7.5x54mm French',
    caliberMm: 7.5,
    muzzleVelocity: 823,
    projectileMassKg: 0.009,
    practicalRPM: 15,
    magazineSize: 5,
    reloadSeconds: 3.8,
    carriedAmmo: 60,
    dispersionMOA: 2.8,
    maxRange: 500,
    woundDamage: 112
  }),
  LEBEL_M1886_M93: freezeWeapon({
    id: 'LEBEL_M1886_M93',
    name: 'Lebel Mle 1886/93',
    kind: 'rifle',
    cartridge: '8 mm French service cartridge',
    caliberMm: 8,
    ...FRENCH_8MM_RIFLE_GAMEPLAY_APPROXIMATION,
    magazineSize: 8,
    carriedAmmo: 120,
    lengthMeters: 1.3,
    feedType: 'tubular_magazine',
    feedDataQuality: 'historical eight-round tubular magazine',
    issueDataQuality:
      'historical First World War infantry issue; not evidence of a universal 1940 allocation',
    ballisticsDataQuality: FRENCH_8MM_RIFLE_BALLISTICS_QUALITY,
    reloadDataQuality:
      '3.8-second reload is a gameplay approximation reusing the current MAS-36 family baseline',
    dataQuality:
      'historical weapon identity, length, feed, and First World War issue; runtime ballistics, cadence, and the 3.8-second reload are gameplay approximations',
    referenceUrl: LEBEL_MUSEUM_REFERENCE
  }),
  BERTHIER_M1907_15_M16: freezeWeapon({
    id: 'BERTHIER_M1907_15_M16',
    name: 'Berthier Mle 1907/15 M16',
    kind: 'rifle',
    cartridge: '8 mm French service cartridge',
    caliberMm: 8,
    ...FRENCH_8MM_RIFLE_GAMEPLAY_APPROXIMATION,
    magazineSize: 5,
    carriedAmmo: 60,
    feedDataQuality:
      'five-round M16 capacity is an inferred gameplay value pending a primary technical source',
    issueDataQuality:
      '60-round carried load is a gameplay approximation; formation-dependent 1940 allocation remains unresolved',
    serviceDataQuality:
      'museum collection documents this model in the theoretical metropolitan-infantry equipment issue of 3 September 1939',
    compatibleOpticIds: Object.freeze(['APX_1916']),
    opticDataQuality:
      'historical First World War APX 1916 compatibility with the Berthier 07/15; not evidence of a 1940 allocation',
    ballisticsDataQuality: FRENCH_8MM_RIFLE_BALLISTICS_QUALITY,
    dataQuality:
      'historical weapon identity and documented theoretical 3 September 1939 equipment context; feed capacity is inferred and runtime ballistics, cadence, reload, and carried load are gameplay approximations',
    referenceUrl: BERTHIER_1940_MUSEUM_REFERENCE,
    opticReferenceUrl: APX_1916_MUSEUM_REFERENCE
  }),
  BERTHIER_M1892_M16: freezeWeapon({
    id: 'BERTHIER_M1892_M16',
    name: 'Berthier Mousqueton Mle 1892 M16',
    kind: 'rifle',
    cartridge: '8 mm French service cartridge',
    caliberMm: 8,
    ...FRENCH_8MM_RIFLE_GAMEPLAY_APPROXIMATION,
    magazineSize: 5,
    carriedAmmo: 60,
    feedDataQuality:
      'five-round M16 capacity is an inferred gameplay value pending a primary technical source',
    issueDataQuality:
      '60-round carried load is a gameplay approximation; role-specific 1940 distribution remains unresolved',
    identityDataQuality:
      'the exact Mle 1892 M16 designation remains pending a direct official or archival reference; the cited museum source supports only the broader Berthier mounted-troop origin and system service context',
    serviceDataQuality:
      'historical mounted-troop design context and Berthier-system service into the Second World War',
    ballisticsDataQuality: FRENCH_8MM_RIFLE_BALLISTICS_QUALITY,
    dataQuality:
      'provisional exact weapon identity pending direct official or archival provenance; broader service context is historical, feed capacity is inferred, and runtime ballistics, cadence, reload, and carried load are gameplay approximations',
    referenceUrl: BERTHIER_MUSEUM_REFERENCE
  }),
  LEBEL_M1886_M93_APX1916: freezeWeapon({
    id: 'LEBEL_M1886_M93_APX1916',
    name: 'Lebel Mle 1886/93 with APX 1916',
    kind: 'rifle',
    cartridge: '8 mm French service cartridge',
    caliberMm: 8,
    ...FRENCH_8MM_RIFLE_GAMEPLAY_APPROXIMATION,
    magazineSize: 8,
    carriedAmmo: 60,
    lengthMeters: 1.3,
    feedType: 'tubular_magazine',
    feedDataQuality: 'historical eight-round tubular magazine',
    issueDataQuality:
      '60-round carried load is a gameplay approximation; scoped-rifle allocation in 1940 remains unresolved',
    opticId: 'APX_1916',
    opticDataQuality:
      'historical First World War Lebel optic configuration; not evidence of a 1940 allocation',
    ballisticsDataQuality: FRENCH_8MM_RIFLE_BALLISTICS_QUALITY,
    dataQuality:
      'historical weapon and optic identity; runtime ballistics, cadence, reload, and carried load are gameplay approximations',
    referenceUrl: APX_1916_MUSEUM_REFERENCE,
    weaponReferenceUrl: LEBEL_MUSEUM_REFERENCE
  }),
  BRANDT_MLE1935_60MM_HE: freezeWeapon({
    id: 'BRANDT_MLE1935_60MM_HE',
    name: 'Brandt Mle 1935 60 mm mortar HE',
    kind: 'mortar_he',
    cartridge: '60 mm fin-stabilized mortar bomb',
    caliberMm: 60,
    muzzleVelocity: 90,
    minimumMuzzleVelocity: 15,
    mortarElevationDegrees: 65,
    projectileMassKg: 1.3,
    dragPerSecond: 0,
    practicalRPM: 13.333333333333334,
    magazineSize: 1,
    reloadSeconds: 4.5,
    carriedAmmo: 24,
    dispersionMOA: 35,
    minimumRangeMeters: 25,
    maxRange: 600,
    tracerEvery: 0,
    explosiveRadius: 5.2,
    woundDamage: 190,
    identityDataQuality:
      'historical weapon identity and February 1936 French Ministry of War provisional instruction, amended through February 1940',
    ballisticsDataQuality:
      'velocity envelope, fixed 65-degree solver elevation, drag, dispersion, minimum and maximum runtime ranges are gameplay approximations',
    ammunitionDataQuality:
      'projectile mass, explosive radius, wound effect, cadence, reload time, and 24-round team allocation are gameplay approximations',
    dataQuality:
      'historical weapon identity; all current runtime ballistics, effects, cadence, and ammunition quantities are explicit gameplay approximations',
    referenceUrl: BRANDT_MLE1935_MANUAL_REFERENCE
  }),
  FM2429: freezeWeapon({
    id: 'FM2429',
    name: 'FM 24/29 LMG',
    kind: 'machine_gun',
    cartridge: '7.5x54mm French',
    caliberMm: 7.5,
    muzzleVelocity: 830,
    projectileMassKg: 0.009,
    cyclicRPM: 450,
    practicalRPM: 140,
    magazineSize: 25,
    reloadSeconds: 3.2,
    carriedAmmo: 250,
    burstSize: 4,
    dispersionMOA: 4.2,
    maxRange: 650,
    woundDamage: 114
  }),
  MAS38: freezeWeapon({
    id: 'MAS38',
    name: 'MAS-38 SMG',
    kind: 'submachine_gun',
    cartridge: '7.65x20mm Longue',
    caliberMm: 7.65,
    muzzleVelocity: 350,
    projectileMassKg: 0.005,
    dragPerSecond: 0.13,
    cyclicRPM: 600,
    practicalRPM: 90,
    magazineSize: 32,
    reloadSeconds: 2.8,
    carriedAmmo: 160,
    burstSize: 3,
    dispersionMOA: 6.5,
    maxRange: 160,
    woundDamage: 82
  }),
  KAR98K: freezeWeapon({
    id: 'KAR98K',
    name: 'Kar98k',
    kind: 'rifle',
    cartridge: '7.92x57mm Mauser',
    caliberMm: 7.92,
    muzzleVelocity: 760,
    projectileMassKg: 0.01155,
    practicalRPM: 15,
    magazineSize: 5,
    reloadSeconds: 4.1,
    carriedAmmo: 60,
    dispersionMOA: 2.6,
    maxRange: 500,
    woundDamage: 120
  }),
  MG34: freezeWeapon({
    id: 'MG34',
    name: 'MG34 LMG',
    kind: 'machine_gun',
    cartridge: '7.92x57mm Mauser',
    caliberMm: 7.92,
    muzzleVelocity: 755,
    projectileMassKg: 0.01155,
    cyclicRPM: 900,
    practicalRPM: 110,
    magazineSize: 50,
    reloadSeconds: 4.3,
    carriedAmmo: 300,
    burstSize: 5,
    dispersionMOA: 4.5,
    maxRange: 700,
    woundDamage: 120
  }),
  MAC31_VEHICLE: freezeWeapon({
    id: 'MAC31_VEHICLE',
    name: '7.5mm MAC mle 1931 vehicle machine gun',
    kind: 'machine_gun',
    cartridge: '7.5x54mm French',
    caliberMm: 7.5,
    muzzleVelocity: 830,
    projectileMassKg: 0.009,
    cyclicRPM: 750,
    practicalRPM: 150,
    magazineSize: 150,
    reloadSeconds: 5.5,
    carriedAmmo: 2550,
    burstSize: 5,
    dispersionMOA: 5.2,
    maxRange: 700,
    woundDamage: 114,
    dataQuality: 'historical weapon identity, caliber, 150-round drum, and nominal cyclic cadence; reload and practical cadence are gameplay approximations',
    referenceUrl: 'https://www.chars-francais.net/index.php?catid=13&id=2026%3A1935-somua-s-35&view=article'
  }),
  MG34_VEHICLE: freezeWeapon({
    id: 'MG34_VEHICLE',
    name: '7.92mm MG 34 vehicle machine gun',
    kind: 'machine_gun',
    cartridge: '7.92x57mm Mauser',
    caliberMm: 7.92,
    muzzleVelocity: 755,
    projectileMassKg: 0.01155,
    cyclicRPM: 850,
    practicalRPM: 200,
    magazineSize: 150,
    reloadSeconds: 6,
    carriedAmmo: 2700,
    burstSize: 5,
    dispersionMOA: 5,
    maxRange: 800,
    woundDamage: 120,
    dataQuality: 'historical weapon identity, caliber, and bounded cyclic-rate range; 150-round vehicle feed, reload, and practical cadence are gameplay approximations',
    referenceUrl: 'https://tankmuseum.org/article/live-round-panzer-iii'
  }),
  MG37T_VEHICLE: freezeWeapon({
    id: 'MG37T_VEHICLE',
    name: '7.92mm MG 37(t) vehicle machine gun',
    kind: 'machine_gun',
    cartridge: '7.92x57mm Mauser',
    caliberMm: 7.92,
    muzzleVelocity: 793,
    projectileMassKg: 0.01155,
    cyclicRPM: 500,
    practicalRPM: 180,
    magazineSize: 100,
    reloadSeconds: 5.5,
    carriedAmmo: 2700,
    burstSize: 5,
    dispersionMOA: 5.2,
    maxRange: 750,
    woundDamage: 120,
    dataQuality: 'historical weapon identity and caliber; velocity, feed capacity, reload, and cadence are bounded gameplay approximations'
  }),
  MP40: freezeWeapon({
    id: 'MP40',
    name: 'MP40',
    kind: 'submachine_gun',
    cartridge: '9x19mm Parabellum',
    caliberMm: 9,
    muzzleVelocity: 380,
    projectileMassKg: 0.008,
    dragPerSecond: 0.12,
    cyclicRPM: 500,
    practicalRPM: 180,
    magazineSize: 32,
    reloadSeconds: 3.1,
    carriedAmmo: 192,
    burstSize: 3,
    dispersionMOA: 6.2,
    maxRange: 180,
    woundDamage: 88
  }),
  SA35_AP: freezeWeapon({
    id: 'SA35_AP',
    name: '47mm SA 35 AP',
    kind: 'cannon_ap',
    cartridge: '47x193mmR',
    caliberMm: 47,
    muzzleVelocity: 660,
    projectileMassKg: 1.62,
    dragPerSecond: 0.035,
    practicalRPM: 6,
    magazineSize: 1,
    reloadSeconds: 7.8,
    carriedAmmo: 118,
    dispersionMOA: 1.7,
    maxRange: 1200,
    tracerEvery: 1,
    penetrationMmAt100m: 40,
    woundDamage: 260
  }),
  SA35_HE: freezeWeapon({
    id: 'SA35_HE',
    name: '47mm SA 35 HE',
    kind: 'cannon_he',
    cartridge: '47x193mmR',
    caliberMm: 47,
    muzzleVelocity: 590,
    projectileMassKg: 1.42,
    dragPerSecond: 0.04,
    practicalRPM: 6,
    magazineSize: 1,
    reloadSeconds: 7.8,
    carriedAmmo: 118,
    dispersionMOA: 2,
    maxRange: 1000,
    tracerEvery: 1,
    explosiveRadius: 5.5,
    woundDamage: 220
  }),
  ABS_SA35_75_HE: freezeWeapon({
    id: 'ABS_SA35_75_HE',
    name: '75mm ABS SA 35 HE',
    kind: 'cannon_he',
    cartridge: '75mm French hull-gun HE',
    caliberMm: 75,
    muzzleVelocity: 500,
    projectileMassKg: 5.55,
    explosiveFillKg: 0.74,
    dragPerSecond: 0.045,
    theoreticalRPM: 15,
    practicalRPM: 6,
    sustainedPracticalRPM: 3,
    readyFusedRounds: 6,
    magazineSize: 1,
    reloadSeconds: 10,
    carriedAmmo: 67,
    dispersionMOA: 2.8,
    maxRange: 1600,
    tracerEvery: 1,
    explosiveRadius: 9,
    woundDamage: 360,
    dataQuality: 'secondary technical synthesis citing the B1 bis manual for shell identity, 5.55 kg mass, 0.74 kg explosive fill, 500 m/s velocity, 1,600 m sight ladder, 15 rpm theoretical cadence, six ready-fused HE rounds, and 67-round allocation; 6 rpm initial and 3 rpm post-ready-fuse runtime cadence, reload timing, dispersion, and blast radius are gameplay approximations',
    referenceUrl: 'https://tanks-encyclopedia.com/ww2/france/char_b1_bis.php#the-naeder-steering-system-8'
  }),
  ABS_SA35_75_APHE: freezeWeapon({
    id: 'ABS_SA35_75_APHE',
    name: '75mm ABS Obus de rupture Mle 1910M APHE',
    kind: 'cannon_aphe',
    cartridge: '75mm Obus de rupture Mle 1910M',
    caliberMm: 75,
    muzzleVelocity: 470,
    projectileMassKg: 6.4,
    explosiveFillKg: 0.09,
    dragPerSecond: 0.042,
    theoreticalRPM: 15,
    practicalRPM: 6,
    magazineSize: 1,
    reloadSeconds: 10,
    carriedAmmo: 7,
    dispersionMOA: 3,
    maxRange: 1560,
    tracerEvery: 1,
    penetrationMmAt100m: 44,
    penetrationVelocityExponent: 0.35,
    penetrationReference: Object.freeze({
      thicknessMm: 40,
      rangeMeters: 400,
      incidenceDegrees: 30
    }),
    explosiveRadius: 2.8,
    woundDamage: 300,
    dataQuality: 'secondary technical synthesis citing the B1 bis manual for Mle 1910M APHE identity, 6.4 kg mass, 0.09 kg explosive fill, 470 m/s velocity, 40 mm at 400 m and 30-degree incidence penetration datum, 1,560 m sight ladder, and seven-round allocation; 44 mm runtime penetration baseline, velocity exponent, reload timing, dispersion, and blast radius are gameplay approximations',
    referenceUrl: 'https://tanks-encyclopedia.com/ww2/france/char_b1_bis.php#the-naeder-steering-system-8'
  }),
  KWK36_AP: freezeWeapon({
    id: 'KWK36_AP',
    name: '3.7cm KwK 36 AP',
    kind: 'cannon_ap',
    cartridge: '37x249mmR',
    caliberMm: 37,
    muzzleVelocity: 745,
    projectileMassKg: 0.685,
    dragPerSecond: 0.042,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.5,
    carriedAmmo: 120,
    dispersionMOA: 1.8,
    maxRange: 1100,
    tracerEvery: 1,
    penetrationMmAt100m: 36,
    woundDamage: 230
  }),
  KWK36_HE: freezeWeapon({
    id: 'KWK36_HE',
    name: '3.7cm KwK 36 HE',
    kind: 'cannon_he',
    cartridge: '37x249mmR',
    caliberMm: 37,
    muzzleVelocity: 680,
    projectileMassKg: 0.615,
    dragPerSecond: 0.045,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.5,
    carriedAmmo: 120,
    dispersionMOA: 2,
    maxRange: 1000,
    tracerEvery: 1,
    explosiveRadius: 4.2,
    woundDamage: 190
  }),
  SA18_AP: freezeWeapon({
    id: 'SA18_AP',
    name: '37mm SA 18 AP',
    kind: 'cannon_ap',
    cartridge: '37x94mmR',
    caliberMm: 37,
    muzzleVelocity: 388,
    projectileMassKg: 0.5,
    dragPerSecond: 0.052,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.8,
    carriedAmmo: 58,
    dispersionMOA: 2.4,
    maxRange: 700,
    tracerEvery: 1,
    penetrationMmAt100m: 12,
    woundDamage: 170,
    dataQuality: 'historical weapon; penetration and cadence are bounded gameplay approximations'
  }),
  SA18_HE: freezeWeapon({
    id: 'SA18_HE',
    name: '37mm SA 18 HE',
    kind: 'cannon_he',
    cartridge: '37x94mmR',
    caliberMm: 37,
    muzzleVelocity: 367,
    projectileMassKg: 0.555,
    dragPerSecond: 0.054,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.8,
    carriedAmmo: 58,
    dispersionMOA: 2.6,
    maxRange: 700,
    tracerEvery: 1,
    explosiveRadius: 3.3,
    woundDamage: 165,
    dataQuality: 'historical weapon; explosive effect and cadence are gameplay approximations'
  }),
  SA38_AP: freezeWeapon({
    id: 'SA38_AP',
    name: '37mm SA 38 AP',
    kind: 'cannon_ap',
    cartridge: '37x149mmR',
    caliberMm: 37,
    muzzleVelocity: 701,
    projectileMassKg: 0.7,
    dragPerSecond: 0.043,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.3,
    carriedAmmo: 100,
    dispersionMOA: 1.9,
    maxRange: 1000,
    tracerEvery: 1,
    penetrationMmAt100m: 30,
    woundDamage: 215,
    dataQuality: 'historical weapon; penetration and cadence are bounded gameplay approximations'
  }),
  SA38_HE: freezeWeapon({
    id: 'SA38_HE',
    name: '37mm SA 38 HE',
    kind: 'cannon_he',
    cartridge: '37x149mmR',
    caliberMm: 37,
    muzzleVelocity: 600,
    projectileMassKg: 0.7,
    dragPerSecond: 0.046,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.3,
    carriedAmmo: 100,
    dispersionMOA: 2.1,
    maxRange: 900,
    tracerEvery: 1,
    explosiveRadius: 4.0,
    woundDamage: 185,
    dataQuality: 'historical weapon family; projectile velocity and explosive effect are gameplay approximations'
  }),
  SA35_25_AP: freezeWeapon({
    id: 'SA35_25_AP',
    name: '25mm SA 35 AP',
    kind: 'cannon_ap',
    cartridge: '25x194mmR',
    caliberMm: 25,
    muzzleVelocity: 950,
    projectileMassKg: 0.32,
    dragPerSecond: 0.047,
    practicalRPM: 15,
    magazineSize: 1,
    reloadSeconds: 4.5,
    carriedAmmo: 150,
    dispersionMOA: 1.8,
    maxRange: 1100,
    tracerEvery: 1,
    penetrationMmAt100m: 40,
    woundDamage: 185,
    dataQuality: 'historical AP-only 1940 load; terminal effect is a gameplay approximation'
  }),
  KWK30_AP: freezeWeapon({
    id: 'KWK30_AP',
    name: '2cm KwK 30 AP',
    kind: 'cannon_ap',
    cartridge: '20x138mmB',
    caliberMm: 20,
    muzzleVelocity: 780,
    projectileMassKg: 0.148,
    dragPerSecond: 0.05,
    cyclicRPM: 280,
    practicalRPM: 120,
    magazineSize: 10,
    reloadSeconds: 4.2,
    carriedAmmo: 180,
    burstSize: 3,
    dispersionMOA: 2.5,
    maxRange: 900,
    tracerEvery: 1,
    penetrationMmAt100m: 23,
    woundDamage: 155,
    dataQuality: 'historical 10-round feed and weapon family; penetration is a bounded gameplay approximation'
  }),
  KWK30_HE: freezeWeapon({
    id: 'KWK30_HE',
    name: '2cm KwK 30 HE',
    kind: 'cannon_he',
    cartridge: '20x138mmB',
    caliberMm: 20,
    muzzleVelocity: 900,
    projectileMassKg: 0.12,
    dragPerSecond: 0.052,
    cyclicRPM: 280,
    practicalRPM: 120,
    magazineSize: 10,
    reloadSeconds: 4.2,
    carriedAmmo: 180,
    burstSize: 3,
    dispersionMOA: 2.7,
    maxRange: 850,
    tracerEvery: 1,
    explosiveRadius: 2.4,
    woundDamage: 145,
    dataQuality: 'historical 10-round feed and weapon family; explosive effect is a gameplay approximation'
  }),
  KWK34T_AP: freezeWeapon({
    id: 'KWK34T_AP',
    name: '3.7cm KwK 34(t) AP',
    kind: 'cannon_ap',
    cartridge: '37x268mmR',
    caliberMm: 37,
    muzzleVelocity: 690,
    projectileMassKg: 0.815,
    dragPerSecond: 0.042,
    practicalRPM: 12,
    magazineSize: 1,
    reloadSeconds: 5.2,
    carriedAmmo: 78,
    dispersionMOA: 1.8,
    maxRange: 1100,
    tracerEvery: 1,
    penetrationMmAt100m: 37,
    woundDamage: 225,
    dataQuality: 'historical weapon family; penetration and cadence are bounded gameplay approximations'
  }),
  KWK34T_HE: freezeWeapon({
    id: 'KWK34T_HE',
    name: '3.7cm KwK 34(t) HE',
    kind: 'cannon_he',
    cartridge: '37x268mmR',
    caliberMm: 37,
    muzzleVelocity: 600,
    projectileMassKg: 0.82,
    dragPerSecond: 0.045,
    practicalRPM: 12,
    magazineSize: 1,
    reloadSeconds: 5.2,
    carriedAmmo: 78,
    dispersionMOA: 2,
    maxRange: 1000,
    tracerEvery: 1,
    explosiveRadius: 4.2,
    woundDamage: 190,
    dataQuality: 'historical weapon family; projectile velocity and explosive effect are gameplay approximations'
  }),
  KWK38T_AP: freezeWeapon({
    id: 'KWK38T_AP',
    name: '3.7cm KwK 38(t) AP',
    kind: 'cannon_ap',
    cartridge: '37x268mmR',
    caliberMm: 37,
    muzzleVelocity: 750,
    projectileMassKg: 0.815,
    dragPerSecond: 0.041,
    practicalRPM: 12,
    magazineSize: 1,
    reloadSeconds: 5.0,
    carriedAmmo: 90,
    dispersionMOA: 1.7,
    maxRange: 1150,
    tracerEvery: 1,
    penetrationMmAt100m: 39,
    woundDamage: 230,
    dataQuality: 'historical weapon family; penetration and cadence are bounded gameplay approximations'
  }),
  KWK38T_HE: freezeWeapon({
    id: 'KWK38T_HE',
    name: '3.7cm KwK 38(t) HE',
    kind: 'cannon_he',
    cartridge: '37x268mmR',
    caliberMm: 37,
    muzzleVelocity: 600,
    projectileMassKg: 0.82,
    dragPerSecond: 0.045,
    practicalRPM: 12,
    magazineSize: 1,
    reloadSeconds: 5.0,
    carriedAmmo: 90,
    dispersionMOA: 2,
    maxRange: 1000,
    tracerEvery: 1,
    explosiveRadius: 4.2,
    woundDamage: 190,
    dataQuality: 'historical weapon family; projectile velocity and explosive effect are gameplay approximations'
  }),
  KWK37_AP: freezeWeapon({
    id: 'KWK37_AP',
    name: '7.5cm KwK 37 L/24 AP',
    kind: 'cannon_ap',
    cartridge: '75x243mmR',
    caliberMm: 75,
    muzzleVelocity: 385,
    projectileMassKg: 6.8,
    dragPerSecond: 0.033,
    practicalRPM: 8,
    magazineSize: 1,
    reloadSeconds: 6.5,
    carriedAmmo: 80,
    dispersionMOA: 1.9,
    maxRange: 1000,
    tracerEvery: 1,
    penetrationMmAt100m: 41,
    woundDamage: 310,
    dataQuality: 'historical weapon and projectile class; penetration is a bounded gameplay approximation'
  }),
  KWK37_HE: freezeWeapon({
    id: 'KWK37_HE',
    name: '7.5cm KwK 37 L/24 HE',
    kind: 'cannon_he',
    cartridge: '75x243mmR',
    caliberMm: 75,
    muzzleVelocity: 420,
    projectileMassKg: 5.74,
    dragPerSecond: 0.036,
    practicalRPM: 8,
    magazineSize: 1,
    reloadSeconds: 6.5,
    carriedAmmo: 80,
    dispersionMOA: 2.1,
    maxRange: 1200,
    tracerEvery: 1,
    explosiveRadius: 8.5,
    woundDamage: 300,
    dataQuality: 'historical weapon and projectile class; explosive effect is a gameplay approximation'
  })
});

const NAME_TO_ID = Object.freeze({
  'MAS-36 Rifle': 'MAS36',
  'Lebel Mle 1886/93': 'LEBEL_M1886_M93',
  'Berthier Mle 1907/15 M16': 'BERTHIER_M1907_15_M16',
  'Berthier Mousqueton Mle 1892 M16': 'BERTHIER_M1892_M16',
  'Lebel Mle 1886/93 with APX 1916': 'LEBEL_M1886_M93_APX1916',
  'Brandt Mle 1935 60 mm mortar HE': 'BRANDT_MLE1935_60MM_HE',
  'FM 24/29 LMG': 'FM2429',
  'MAS-38 SMG': 'MAS38',
  Kar98k: 'KAR98K',
  'MG34 LMG': 'MG34',
  MP40: 'MP40'
});

export function weaponIdFromName(name) {
  return NAME_TO_ID[name] ?? name ?? null;
}

export function getWeapon(idOrName) {
  return FRANCE_1940_WEAPONS[weaponIdFromName(idOrName)] ?? null;
}
