const freezeWeapon = (weapon) => Object.freeze({
  burstSize: 1,
  cyclicRPM: weapon.practicalRPM,
  dragPerSecond: 0.08,
  dispersionMOA: 3,
  maxRange: 500,
  tracerEvery: 4,
  explosiveRadius: 0,
  penetrationMmAt100m: 0,
  penetrationVelocityExponent: 1.35,
  ...weapon
});

export const FRANCE_1940_WEAPONS = Object.freeze({
  MAS36: freezeWeapon({
    id: 'MAS36',
    name: 'MAS-36 Rifle',
    kind: 'rifle',
    cartridge: '7.5x54mm French',
    caliberMm: 7.5,
    muzzleVelocity: 823,
    projectileMassKg: 0.009,
    practicalRPM: 15,
    magazineSize: 5,
    reloadSeconds: 3.8,
    carriedAmmo: 60,
    dispersionMOA: 2.8,
    maxRange: 500,
    woundDamage: 112
  }),
  FM2429: freezeWeapon({
    id: 'FM2429',
    name: 'FM 24/29 LMG',
    kind: 'machine_gun',
    cartridge: '7.5x54mm French',
    caliberMm: 7.5,
    muzzleVelocity: 830,
    projectileMassKg: 0.009,
    cyclicRPM: 450,
    practicalRPM: 140,
    magazineSize: 25,
    reloadSeconds: 3.2,
    carriedAmmo: 250,
    burstSize: 4,
    dispersionMOA: 4.2,
    maxRange: 650,
    woundDamage: 114
  }),
  MAS38: freezeWeapon({
    id: 'MAS38',
    name: 'MAS-38 SMG',
    kind: 'submachine_gun',
    cartridge: '7.65x20mm Longue',
    caliberMm: 7.65,
    muzzleVelocity: 350,
    projectileMassKg: 0.005,
    dragPerSecond: 0.13,
    cyclicRPM: 600,
    practicalRPM: 90,
    magazineSize: 32,
    reloadSeconds: 2.8,
    carriedAmmo: 160,
    burstSize: 3,
    dispersionMOA: 6.5,
    maxRange: 160,
    woundDamage: 82
  }),
  KAR98K: freezeWeapon({
    id: 'KAR98K',
    name: 'Kar98k',
    kind: 'rifle',
    cartridge: '7.92x57mm Mauser',
    caliberMm: 7.92,
    muzzleVelocity: 760,
    projectileMassKg: 0.01155,
    practicalRPM: 15,
    magazineSize: 5,
    reloadSeconds: 4.1,
    carriedAmmo: 60,
    dispersionMOA: 2.6,
    maxRange: 500,
    woundDamage: 120
  }),
  MG34: freezeWeapon({
    id: 'MG34',
    name: 'MG34 LMG',
    kind: 'machine_gun',
    cartridge: '7.92x57mm Mauser',
    caliberMm: 7.92,
    muzzleVelocity: 755,
    projectileMassKg: 0.01155,
    cyclicRPM: 900,
    practicalRPM: 110,
    magazineSize: 50,
    reloadSeconds: 4.3,
    carriedAmmo: 300,
    burstSize: 5,
    dispersionMOA: 4.5,
    maxRange: 700,
    woundDamage: 120
  }),
  MAC31_VEHICLE: freezeWeapon({
    id: 'MAC31_VEHICLE',
    name: '7.5mm MAC mle 1931 vehicle machine gun',
    kind: 'machine_gun',
    cartridge: '7.5x54mm French',
    caliberMm: 7.5,
    muzzleVelocity: 830,
    projectileMassKg: 0.009,
    cyclicRPM: 750,
    practicalRPM: 150,
    magazineSize: 150,
    reloadSeconds: 5.5,
    carriedAmmo: 2550,
    burstSize: 5,
    dispersionMOA: 5.2,
    maxRange: 700,
    woundDamage: 114,
    dataQuality: 'historical weapon identity, caliber, 150-round drum, and nominal cyclic cadence; reload and practical cadence are gameplay approximations',
    referenceUrl: 'https://www.chars-francais.net/index.php?catid=13&id=2026%3A1935-somua-s-35&view=article'
  }),
  MG34_VEHICLE: freezeWeapon({
    id: 'MG34_VEHICLE',
    name: '7.92mm MG 34 vehicle machine gun',
    kind: 'machine_gun',
    cartridge: '7.92x57mm Mauser',
    caliberMm: 7.92,
    muzzleVelocity: 755,
    projectileMassKg: 0.01155,
    cyclicRPM: 850,
    practicalRPM: 200,
    magazineSize: 150,
    reloadSeconds: 6,
    carriedAmmo: 2700,
    burstSize: 5,
    dispersionMOA: 5,
    maxRange: 800,
    woundDamage: 120,
    dataQuality: 'historical weapon identity, caliber, and bounded cyclic-rate range; 150-round vehicle feed, reload, and practical cadence are gameplay approximations',
    referenceUrl: 'https://tankmuseum.org/article/live-round-panzer-iii'
  }),
  MG37T_VEHICLE: freezeWeapon({
    id: 'MG37T_VEHICLE',
    name: '7.92mm MG 37(t) vehicle machine gun',
    kind: 'machine_gun',
    cartridge: '7.92x57mm Mauser',
    caliberMm: 7.92,
    muzzleVelocity: 793,
    projectileMassKg: 0.01155,
    cyclicRPM: 500,
    practicalRPM: 180,
    magazineSize: 100,
    reloadSeconds: 5.5,
    carriedAmmo: 2700,
    burstSize: 5,
    dispersionMOA: 5.2,
    maxRange: 750,
    woundDamage: 120,
    dataQuality: 'historical weapon identity and caliber; velocity, feed capacity, reload, and cadence are bounded gameplay approximations'
  }),
  MP40: freezeWeapon({
    id: 'MP40',
    name: 'MP40',
    kind: 'submachine_gun',
    cartridge: '9x19mm Parabellum',
    caliberMm: 9,
    muzzleVelocity: 380,
    projectileMassKg: 0.008,
    dragPerSecond: 0.12,
    cyclicRPM: 500,
    practicalRPM: 180,
    magazineSize: 32,
    reloadSeconds: 3.1,
    carriedAmmo: 192,
    burstSize: 3,
    dispersionMOA: 6.2,
    maxRange: 180,
    woundDamage: 88
  }),
  SA35_AP: freezeWeapon({
    id: 'SA35_AP',
    name: '47mm SA 35 AP',
    kind: 'cannon_ap',
    cartridge: '47x193mmR',
    caliberMm: 47,
    muzzleVelocity: 660,
    projectileMassKg: 1.62,
    dragPerSecond: 0.035,
    practicalRPM: 6,
    magazineSize: 1,
    reloadSeconds: 7.8,
    carriedAmmo: 118,
    dispersionMOA: 1.7,
    maxRange: 1200,
    tracerEvery: 1,
    penetrationMmAt100m: 40,
    woundDamage: 260
  }),
  SA35_HE: freezeWeapon({
    id: 'SA35_HE',
    name: '47mm SA 35 HE',
    kind: 'cannon_he',
    cartridge: '47x193mmR',
    caliberMm: 47,
    muzzleVelocity: 590,
    projectileMassKg: 1.42,
    dragPerSecond: 0.04,
    practicalRPM: 6,
    magazineSize: 1,
    reloadSeconds: 7.8,
    carriedAmmo: 118,
    dispersionMOA: 2,
    maxRange: 1000,
    tracerEvery: 1,
    explosiveRadius: 5.5,
    woundDamage: 220
  }),
  KWK36_AP: freezeWeapon({
    id: 'KWK36_AP',
    name: '3.7cm KwK 36 AP',
    kind: 'cannon_ap',
    cartridge: '37x249mmR',
    caliberMm: 37,
    muzzleVelocity: 745,
    projectileMassKg: 0.685,
    dragPerSecond: 0.042,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.5,
    carriedAmmo: 120,
    dispersionMOA: 1.8,
    maxRange: 1100,
    tracerEvery: 1,
    penetrationMmAt100m: 36,
    woundDamage: 230
  }),
  KWK36_HE: freezeWeapon({
    id: 'KWK36_HE',
    name: '3.7cm KwK 36 HE',
    kind: 'cannon_he',
    cartridge: '37x249mmR',
    caliberMm: 37,
    muzzleVelocity: 680,
    projectileMassKg: 0.615,
    dragPerSecond: 0.045,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.5,
    carriedAmmo: 120,
    dispersionMOA: 2,
    maxRange: 1000,
    tracerEvery: 1,
    explosiveRadius: 4.2,
    woundDamage: 190
  }),
  SA18_AP: freezeWeapon({
    id: 'SA18_AP',
    name: '37mm SA 18 AP',
    kind: 'cannon_ap',
    cartridge: '37x94mmR',
    caliberMm: 37,
    muzzleVelocity: 388,
    projectileMassKg: 0.5,
    dragPerSecond: 0.052,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.8,
    carriedAmmo: 58,
    dispersionMOA: 2.4,
    maxRange: 700,
    tracerEvery: 1,
    penetrationMmAt100m: 12,
    woundDamage: 170,
    dataQuality: 'historical weapon; penetration and cadence are bounded gameplay approximations'
  }),
  SA18_HE: freezeWeapon({
    id: 'SA18_HE',
    name: '37mm SA 18 HE',
    kind: 'cannon_he',
    cartridge: '37x94mmR',
    caliberMm: 37,
    muzzleVelocity: 367,
    projectileMassKg: 0.555,
    dragPerSecond: 0.054,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.8,
    carriedAmmo: 58,
    dispersionMOA: 2.6,
    maxRange: 700,
    tracerEvery: 1,
    explosiveRadius: 3.3,
    woundDamage: 165,
    dataQuality: 'historical weapon; explosive effect and cadence are gameplay approximations'
  }),
  SA38_AP: freezeWeapon({
    id: 'SA38_AP',
    name: '37mm SA 38 AP',
    kind: 'cannon_ap',
    cartridge: '37x149mmR',
    caliberMm: 37,
    muzzleVelocity: 701,
    projectileMassKg: 0.7,
    dragPerSecond: 0.043,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.3,
    carriedAmmo: 100,
    dispersionMOA: 1.9,
    maxRange: 1000,
    tracerEvery: 1,
    penetrationMmAt100m: 30,
    woundDamage: 215,
    dataQuality: 'historical weapon; penetration and cadence are bounded gameplay approximations'
  }),
  SA38_HE: freezeWeapon({
    id: 'SA38_HE',
    name: '37mm SA 38 HE',
    kind: 'cannon_he',
    cartridge: '37x149mmR',
    caliberMm: 37,
    muzzleVelocity: 600,
    projectileMassKg: 0.7,
    dragPerSecond: 0.046,
    practicalRPM: 10,
    magazineSize: 1,
    reloadSeconds: 5.3,
    carriedAmmo: 100,
    dispersionMOA: 2.1,
    maxRange: 900,
    tracerEvery: 1,
    explosiveRadius: 4.0,
    woundDamage: 185,
    dataQuality: 'historical weapon family; projectile velocity and explosive effect are gameplay approximations'
  }),
  SA35_25_AP: freezeWeapon({
    id: 'SA35_25_AP',
    name: '25mm SA 35 AP',
    kind: 'cannon_ap',
    cartridge: '25x194mmR',
    caliberMm: 25,
    muzzleVelocity: 950,
    projectileMassKg: 0.32,
    dragPerSecond: 0.047,
    practicalRPM: 15,
    magazineSize: 1,
    reloadSeconds: 4.5,
    carriedAmmo: 150,
    dispersionMOA: 1.8,
    maxRange: 1100,
    tracerEvery: 1,
    penetrationMmAt100m: 40,
    woundDamage: 185,
    dataQuality: 'historical AP-only 1940 load; terminal effect is a gameplay approximation'
  }),
  KWK30_AP: freezeWeapon({
    id: 'KWK30_AP',
    name: '2cm KwK 30 AP',
    kind: 'cannon_ap',
    cartridge: '20x138mmB',
    caliberMm: 20,
    muzzleVelocity: 780,
    projectileMassKg: 0.148,
    dragPerSecond: 0.05,
    cyclicRPM: 280,
    practicalRPM: 120,
    magazineSize: 10,
    reloadSeconds: 4.2,
    carriedAmmo: 180,
    burstSize: 3,
    dispersionMOA: 2.5,
    maxRange: 900,
    tracerEvery: 1,
    penetrationMmAt100m: 23,
    woundDamage: 155,
    dataQuality: 'historical 10-round feed and weapon family; penetration is a bounded gameplay approximation'
  }),
  KWK30_HE: freezeWeapon({
    id: 'KWK30_HE',
    name: '2cm KwK 30 HE',
    kind: 'cannon_he',
    cartridge: '20x138mmB',
    caliberMm: 20,
    muzzleVelocity: 900,
    projectileMassKg: 0.12,
    dragPerSecond: 0.052,
    cyclicRPM: 280,
    practicalRPM: 120,
    magazineSize: 10,
    reloadSeconds: 4.2,
    carriedAmmo: 180,
    burstSize: 3,
    dispersionMOA: 2.7,
    maxRange: 850,
    tracerEvery: 1,
    explosiveRadius: 2.4,
    woundDamage: 145,
    dataQuality: 'historical 10-round feed and weapon family; explosive effect is a gameplay approximation'
  }),
  KWK34T_AP: freezeWeapon({
    id: 'KWK34T_AP',
    name: '3.7cm KwK 34(t) AP',
    kind: 'cannon_ap',
    cartridge: '37x268mmR',
    caliberMm: 37,
    muzzleVelocity: 690,
    projectileMassKg: 0.815,
    dragPerSecond: 0.042,
    practicalRPM: 12,
    magazineSize: 1,
    reloadSeconds: 5.2,
    carriedAmmo: 78,
    dispersionMOA: 1.8,
    maxRange: 1100,
    tracerEvery: 1,
    penetrationMmAt100m: 37,
    woundDamage: 225,
    dataQuality: 'historical weapon family; penetration and cadence are bounded gameplay approximations'
  }),
  KWK34T_HE: freezeWeapon({
    id: 'KWK34T_HE',
    name: '3.7cm KwK 34(t) HE',
    kind: 'cannon_he',
    cartridge: '37x268mmR',
    caliberMm: 37,
    muzzleVelocity: 600,
    projectileMassKg: 0.82,
    dragPerSecond: 0.045,
    practicalRPM: 12,
    magazineSize: 1,
    reloadSeconds: 5.2,
    carriedAmmo: 78,
    dispersionMOA: 2,
    maxRange: 1000,
    tracerEvery: 1,
    explosiveRadius: 4.2,
    woundDamage: 190,
    dataQuality: 'historical weapon family; projectile velocity and explosive effect are gameplay approximations'
  }),
  KWK38T_AP: freezeWeapon({
    id: 'KWK38T_AP',
    name: '3.7cm KwK 38(t) AP',
    kind: 'cannon_ap',
    cartridge: '37x268mmR',
    caliberMm: 37,
    muzzleVelocity: 750,
    projectileMassKg: 0.815,
    dragPerSecond: 0.041,
    practicalRPM: 12,
    magazineSize: 1,
    reloadSeconds: 5.0,
    carriedAmmo: 90,
    dispersionMOA: 1.7,
    maxRange: 1150,
    tracerEvery: 1,
    penetrationMmAt100m: 39,
    woundDamage: 230,
    dataQuality: 'historical weapon family; penetration and cadence are bounded gameplay approximations'
  }),
  KWK38T_HE: freezeWeapon({
    id: 'KWK38T_HE',
    name: '3.7cm KwK 38(t) HE',
    kind: 'cannon_he',
    cartridge: '37x268mmR',
    caliberMm: 37,
    muzzleVelocity: 600,
    projectileMassKg: 0.82,
    dragPerSecond: 0.045,
    practicalRPM: 12,
    magazineSize: 1,
    reloadSeconds: 5.0,
    carriedAmmo: 90,
    dispersionMOA: 2,
    maxRange: 1000,
    tracerEvery: 1,
    explosiveRadius: 4.2,
    woundDamage: 190,
    dataQuality: 'historical weapon family; projectile velocity and explosive effect are gameplay approximations'
  }),
  KWK37_AP: freezeWeapon({
    id: 'KWK37_AP',
    name: '7.5cm KwK 37 L/24 AP',
    kind: 'cannon_ap',
    cartridge: '75x243mmR',
    caliberMm: 75,
    muzzleVelocity: 385,
    projectileMassKg: 6.8,
    dragPerSecond: 0.033,
    practicalRPM: 8,
    magazineSize: 1,
    reloadSeconds: 6.5,
    carriedAmmo: 80,
    dispersionMOA: 1.9,
    maxRange: 1000,
    tracerEvery: 1,
    penetrationMmAt100m: 41,
    woundDamage: 310,
    dataQuality: 'historical weapon and projectile class; penetration is a bounded gameplay approximation'
  }),
  KWK37_HE: freezeWeapon({
    id: 'KWK37_HE',
    name: '7.5cm KwK 37 L/24 HE',
    kind: 'cannon_he',
    cartridge: '75x243mmR',
    caliberMm: 75,
    muzzleVelocity: 420,
    projectileMassKg: 5.74,
    dragPerSecond: 0.036,
    practicalRPM: 8,
    magazineSize: 1,
    reloadSeconds: 6.5,
    carriedAmmo: 80,
    dispersionMOA: 2.1,
    maxRange: 1200,
    tracerEvery: 1,
    explosiveRadius: 8.5,
    woundDamage: 300,
    dataQuality: 'historical weapon and projectile class; explosive effect is a gameplay approximation'
  })
});

const NAME_TO_ID = Object.freeze({
  'MAS-36 Rifle': 'MAS36',
  'FM 24/29 LMG': 'FM2429',
  'MAS-38 SMG': 'MAS38',
  Kar98k: 'KAR98K',
  'MG34 LMG': 'MG34',
  MP40: 'MP40'
});

export function weaponIdFromName(name) {
  return NAME_TO_ID[name] ?? name ?? null;
}

export function getWeapon(idOrName) {
  return FRANCE_1940_WEAPONS[weaponIdFromName(idOrName)] ?? null;
}

